server:
  port: 8060
  address: 127.0.0.1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${server.address}
    instance-id: ${server.address}:${server.port}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: StreamLine
          uri: lbs://STREAMLINE
          predicates:
            - Path=/streamline/**
        - id: trending
          uri: lbs://TRENDING
          predicates:
            - Path=/trending/**

